# Generated by Django 4.0.2 on 2022-05-30 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='expences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expence', models.CharField(default=None, max_length=50)),
                ('pay', models.FloatField(default=None)),
                ('date', models.DateField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='update_balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_balance', models.FloatField()),
            ],
        ),
    ]
